### ISSUE TITLE
项目 Todo

### ISSUE THREAD

**Issue by Chilfish** [Chilfish/Weibo-archiver#7]
这是该项目的代办

- [x] 修复预览页的一堆 bug（如图片查看、分页等）
- [x] 更换到 [naiveui](https://www.naiveui.com/)
- [x] 优化项目结构 #8 
- [ ] 打包到桌面端，暂时先用 Electron😅
	- [x] 初始化 electron 的项目结构 #9 
	- [x] Sqlite3 数据库 #14
	- [ ] 桌面端对应的 UI、原型开发
- [x] 支持设置自定义图床链接 #25
- [x] 导出和导入相关的数据 #27
- [x] 将 web 预览页改为在线平台，部署到 vercel #27
- [x] 将 web 端迁移到 Nuxt #30 
- [x] 更好的搜索微博 #33 
- [x] 按时间来搜索微博 cfda7f9d8de8b499d4a507fc75df988e2fc361e5, 3d9d430de7aa529941fac35e551fa01a263151da
- [x] 多用户支持 #36 
- [ ] 支持视频、文章
- [ ] 我的收藏
- [ ] 简单的楼中楼评论

目前可能将在 v0.5.0 左右发布桌面端版本，支持 Windows 和 MacOS，敬请期待😇
